<?php
namespace local_bulkinstall\local;

defined('MOODLE_INTERNAL') || die();

/** Shared protocol rules. Generated by workspace/scripts/sync_licensing_runtime.py; no runtime dependency. */
final class licensing_runtime {
    private const STATE_CONFIG = 'licensingactivestate';
    private const STATE_VERSION = 1;
    private const STATE_FIELDS = [
        'activationid', 'environment', 'refreshtoken', 'assertion', 'lastcheck', 'lasterror',
        'emergencyresetavailable', 'sitetoken',
    ];

    /** A token generation identifies one refresh operation, including retries after a lost response. */
    public static function refresh_key(string $activationid, string $token): string {
        $hex = hash('sha256', "108design-refresh-v1\0" . $activationid . "\0" . $token);
        return substr($hex, 0, 8) . '-' . substr($hex, 8, 4) . '-5' . substr($hex, 13, 3)
            . '-a' . substr($hex, 17, 3) . '-' . substr($hex, 20, 12);
    }

    /** Only a signed, explicitly perpetual Free assertion may survive cache expiry. */
    public static function is_permanent_free(array $claims): bool {
        return ($claims['permanent_free'] ?? false) === true
            && str_ends_with((string) ($claims['feature_code'] ?? ''), '.free')
            && ($claims['status'] ?? '') === 'active'
            && array_key_exists('valid_until', $claims) && $claims['valid_until'] === null;
    }

    /** Apply signed business time independently of refresh scheduling and JWT clock tolerance. */
    public static function effective_claims(array $claims, ?int $now = null): array {
        $now = $now ?? time();
        if (is_int($claims['valid_until'] ?? null) && $now >= $claims['valid_until']) {
            $claims['status'] = $now < (int) ($claims['grace_until'] ?? 0) ? 'grace' : 'expired';
        }
        return $claims;
    }

    /** Apply one fail-closed gate matrix to Hub and standalone claims. */
    public static function gate_allows(array $claims, string $licensemodel, bool $graceallowed): bool {
        $claims = self::effective_claims($claims);
        if ($licensemodel === 'permanent_free') {
            return self::is_permanent_free($claims);
        }
        if ($licensemodel !== 'commercial') {
            return false;
        }
        return ($claims['status'] ?? '') === 'active'
            || ($graceallowed && ($claims['status'] ?? '') === 'grace');
    }

    /**
     * Read one complete activation snapshot, falling back to pre-snapshot settings during upgrades.
     *
     * An invalid or cleared snapshot fails closed. It must never expose a mixture of old and new credentials.
     * @return array<string, mixed>
     */
    public static function activation_state(string $component): array {
        $stored = get_config($component, self::STATE_CONFIG);
        if (is_string($stored) && $stored !== '') {
            try {
                $decoded = json_decode($stored, true, 16, JSON_THROW_ON_ERROR);
            } catch (\JsonException) {
                return [];
            }
            if (!is_array($decoded) || ($decoded['version'] ?? null) !== self::STATE_VERSION
                    || ($decoded['active'] ?? null) !== true || !is_array($decoded['state'] ?? null)) {
                return [];
            }
            return array_intersect_key($decoded['state'], array_flip(self::STATE_FIELDS));
        }

        $legacy = [];
        foreach (self::STATE_FIELDS as $name) {
            $value = get_config($component, $name);
            if ($value !== false && $value !== '') {
                $legacy[$name] = $value;
            }
        }
        return $legacy;
    }

    /** Persist the authoritative snapshot before synchronising legacy settings for upgrade compatibility. */
    public static function store_activation_state(string $component, array $state): void {
        $state = array_intersect_key($state, array_flip(self::STATE_FIELDS));
        set_config(self::STATE_CONFIG, json_encode([
            'version' => self::STATE_VERSION,
            'active' => true,
            'state' => $state,
        ], JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR), $component);
        foreach (self::STATE_FIELDS as $name) {
            if (array_key_exists($name, $state) && $state[$name] !== null && $state[$name] !== '') {
                set_config($name, $state[$name], $component);
            } else {
                unset_config($name, $component);
            }
        }
    }

    /** Update selected fields without exposing a partially rotated credential set. */
    public static function update_activation_state(string $component, array $changes): void {
        self::store_activation_state($component, array_replace(self::activation_state($component), $changes));
    }

    /** Write a tombstone first so old split settings cannot become authoritative again. */
    public static function clear_activation_state(string $component): void {
        set_config(self::STATE_CONFIG, json_encode([
            'version' => self::STATE_VERSION,
            'active' => false,
            'state' => [],
        ], JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR), $component);
        foreach (self::STATE_FIELDS as $name) {
            unset_config($name, $component);
        }
    }

    /** Shared rotation then feature lock; reentrant across all adapters and Hub delegation. */
    public static function with_lock(string $feature, callable $operation): mixed {
        // Bundle operations discover several entitlements, sometimes inside an already-held feature lock.
        // Take the installation-wide rotation lock first in every adapter to prevent lock inversion.
        return self::operation_lock('rotation', static fn() =>
            self::operation_lock('feature:' . $feature, $operation));
    }

    private static function operation_lock(string $key, callable $operation): mixed {
        $held = &$GLOBALS['108design_licensing_operation_locks'];
        if (!empty($held[$key])) {
            return $operation();
        }
        $lock = \core\lock\lock_config::get_lock_factory('108design_licensing')->get_lock($key, 30);
        if (!$lock) {
            throw new \moodle_exception('locktimeout');
        }
        $held[$key] = true;
        try {
            return $operation();
        } finally {
            unset($held[$key]);
            $lock->release();
        }
    }

    /** Acquire several feature locks in stable order for an all-or-nothing Hub transition. */
    public static function with_locks(array $features, callable $operation): mixed {
        $features = array_values(array_unique(array_filter($features, 'is_string')));
        sort($features, SORT_STRING);
        $run = $operation;
        foreach (array_reverse($features) as $feature) {
            $next = $run;
            $run = static fn() => self::with_lock($feature, $next);
        }
        return $run();
    }
}
